/**
 * CardGenerator - Generates CDS Cards from payer CRD responses
 *
 * Transforms payer Coverage Requirements Discovery (CRD) responses into
 * well-formed CDS Hooks 2.0 cards per the Da Vinci CRD IG STU 2.1.
 *
 * Card types generated:
 *   1. Coverage Information system action (required by CRD 2.1)
 *   2. Launch DTR SMART App cards (when documentation is needed)
 *   3. External Reference cards (links to payer documentation)
 *   4. Instructions cards (text-based guidance)
 *
 * All cards include proper source attribution per CDS Hooks specification.
 *
 * @see https://hl7.org/fhir/us/davinci-crd/
 * @see https://cds-hooks.hl7.org/2.0/
 */
const { logInfo, logWarn } = require('../operations/common/logging');
const { generateUUID } = require('../utils/uid.util');

/**
 * CRD coverage-information extension URL per Da Vinci CRD IG
 * @type {string}
 */
const COVERAGE_INFO_EXTENSION_URL = 'http://hl7.org/fhir/us/davinci-crd/StructureDefinition/ext-coverage-information';

/**
 * Coverage information coding system per CRD IG
 * @type {string}
 */
const CRD_COVERAGE_INFO_SYSTEM = 'http://hl7.org/fhir/us/davinci-crd/CodeSystem/temp';

/**
 * CDS Hooks card indicator levels
 * @type {Object}
 */
const CARD_INDICATORS = {
    INFO: 'info',
    WARNING: 'warning',
    CRITICAL: 'critical'
};

/**
 * Da Vinci CRD coverage assertion codes
 * @type {Object}
 */
const COVERAGE_ASSERTIONS = {
    /** Service/product is covered */
    COVERED: 'covered',
    /** Service/product is not covered */
    NOT_COVERED: 'not-covered',
    /** Coverage determination requires prior authorization */
    PRIOR_AUTH: 'prior-auth',
    /** Coverage determination requires additional documentation */
    DOCUMENTATION: 'documentation',
    /** Coverage cannot be determined with available information */
    CONDITIONAL: 'conditional'
};

class CardGenerator {
    constructor () {
        /**
         * Default source attribution for cards generated by this platform
         * @type {Object}
         */
        this.platformSource = {
            label: 'FHIR Platform CRD Engine',
            url: process.env.PLATFORM_BASE_URL || undefined,
            icon: process.env.PLATFORM_ICON_URL || undefined
        };
    }

    /**
     * Generates CDS Cards and system actions from a payer CRD response.
     *
     * This is the main entry point that orchestrates card generation based
     * on the payer's response content.
     *
     * @param {Object} params
     * @param {Object} params.payerResponse - The payer's CRD response
     * @param {Object} params.coverage - The FHIR Coverage resource
     * @param {string|null} params.payerIdentifier - Payer organization identifier
     * @param {string} params.serviceId - The CDS service ID
     * @param {import('../multiTenancy/tenantContext').TenantContext} params.tenantContext
     * @returns {{cards: Object[], systemActions: Object[]}}
     */
    generateCards ({
        payerResponse,
        coverage,
        payerIdentifier,
        serviceId,
        tenantContext
    }) {
        const cards = [];
        const systemActions = [];

        if (!payerResponse) {
            return { cards, systemActions };
        }

        // Determine the source attribution for the payer
        const payerSource = this.buildPayerSource(payerResponse, payerIdentifier);

        // Process the payer response based on its structure
        if (payerResponse.cards && Array.isArray(payerResponse.cards)) {
            // Payer returned CDS Hooks cards directly - enrich and forward
            for (const payerCard of payerResponse.cards) {
                const enrichedCard = this.enrichPayerCard(payerCard, payerSource);
                cards.push(enrichedCard);
            }
        }

        if (payerResponse.systemActions && Array.isArray(payerResponse.systemActions)) {
            systemActions.push(...payerResponse.systemActions);
        }

        // Generate the Coverage Information system action (required by CRD 2.1)
        const coverageInfoAction = this.createCoverageInformationAction({
            payerResponse,
            coverage,
            payerSource
        });
        if (coverageInfoAction) {
            systemActions.push(coverageInfoAction);
        }

        // Generate additional cards based on CRD response content
        const coverageAssertion = this.extractCoverageAssertion(payerResponse);

        // If prior auth is required, generate a Launch DTR card
        if (this.isPriorAuthRequired(payerResponse, coverageAssertion)) {
            const dtrCard = this.createLaunchDtrCard({
                payerResponse,
                coverage,
                payerSource,
                tenantContext
            });
            if (dtrCard) {
                cards.push(dtrCard);
            }
        }

        // Generate External Reference cards for payer documentation links
        const externalRefCards = this.createExternalReferenceCards({
            payerResponse,
            payerSource
        });
        cards.push(...externalRefCards);

        // Generate Instructions cards for text-based guidance
        const instructionCards = this.createInstructionCards({
            payerResponse,
            payerSource,
            coverageAssertion
        });
        cards.push(...instructionCards);

        logInfo('Cards generated', {
            cardCount: cards.length,
            systemActionCount: systemActions.length,
            coverageAssertion,
            serviceId,
            payerIdentifier
        });

        return { cards, systemActions };
    }

    /**
     * Builds the source attribution object for a payer.
     * @param {Object} payerResponse - The payer response
     * @param {string|null} payerIdentifier - Payer identifier
     * @returns {Object} CDS Hooks source object
     */
    buildPayerSource (payerResponse, payerIdentifier) {
        // Use payer's self-reported source if available
        if (payerResponse.source) {
            return {
                label: payerResponse.source.label || payerIdentifier || 'Payer',
                url: payerResponse.source.url || undefined,
                icon: payerResponse.source.icon || undefined
            };
        }

        return {
            label: payerIdentifier || 'Payer CRD Service'
        };
    }

    /**
     * Enriches a payer-provided CDS card with platform metadata
     * and ensures it conforms to the CDS Hooks 2.0 specification.
     * @param {Object} payerCard - The card from the payer
     * @param {Object} payerSource - The payer source attribution
     * @returns {Object} Enriched card
     */
    enrichPayerCard (payerCard, payerSource) {
        return {
            uuid: payerCard.uuid || generateUUID(),
            summary: payerCard.summary || 'Coverage Requirements Information',
            detail: payerCard.detail || undefined,
            indicator: payerCard.indicator || CARD_INDICATORS.INFO,
            source: payerCard.source || payerSource,
            suggestions: payerCard.suggestions || undefined,
            selectionBehavior: payerCard.selectionBehavior || undefined,
            overrideReasons: payerCard.overrideReasons || undefined,
            links: payerCard.links || undefined,
            ...(payerCard.extension ? { extension: payerCard.extension } : {})
        };
    }

    /**
     * Creates the Coverage Information system action required by CRD 2.1.
     *
     * This system action updates the relevant order/resource with a
     * coverage-information extension containing the payer's determination.
     *
     * @param {Object} params
     * @param {Object} params.payerResponse - The payer CRD response
     * @param {Object} params.coverage - The FHIR Coverage resource
     * @param {Object} params.payerSource - Source attribution
     * @returns {Object|null} System action or null if no coverage info to convey
     */
    createCoverageInformationAction ({ payerResponse, coverage, payerSource }) {
        const assertion = this.extractCoverageAssertion(payerResponse);
        if (!assertion) {
            return null;
        }

        // Build the coverage-information extension
        const coverageInfoExtension = {
            url: COVERAGE_INFO_EXTENSION_URL,
            extension: [
                {
                    url: 'coverage',
                    valueReference: {
                        reference: coverage.id ? `Coverage/${coverage.id}` : undefined
                    }
                },
                {
                    url: 'covered',
                    valueCode: assertion === COVERAGE_ASSERTIONS.COVERED ||
                        assertion === COVERAGE_ASSERTIONS.PRIOR_AUTH
                        ? 'covered'
                        : assertion === COVERAGE_ASSERTIONS.NOT_COVERED
                            ? 'not-covered'
                            : 'conditional'
                },
                {
                    url: 'pa-needed',
                    valueCode: assertion === COVERAGE_ASSERTIONS.PRIOR_AUTH
                        ? 'auth-needed'
                        : 'no-auth'
                },
                {
                    url: 'doc-needed',
                    valueCode: assertion === COVERAGE_ASSERTIONS.DOCUMENTATION
                        ? 'clinical'
                        : 'no-doc'
                }
            ]
        };

        // Add info-needed reason if coverage is conditional
        if (assertion === COVERAGE_ASSERTIONS.CONDITIONAL && payerResponse.infoNeeded) {
            coverageInfoExtension.extension.push({
                url: 'info-needed',
                valueCode: payerResponse.infoNeeded
            });
        }

        // Add date if provided
        if (payerResponse.coverageDate) {
            coverageInfoExtension.extension.push({
                url: 'date',
                valueDate: payerResponse.coverageDate
            });
        }

        // Add coverage-assertion-id for tracking
        coverageInfoExtension.extension.push({
            url: 'coverage-assertion-id',
            valueString: generateUUID()
        });

        // Add satisfied flag
        coverageInfoExtension.extension.push({
            url: 'satisfied',
            valueBoolean: assertion === COVERAGE_ASSERTIONS.COVERED
        });

        return {
            type: 'update',
            description: `Coverage information from ${payerSource.label}`,
            resource: {
                resourceType: 'Parameters',
                parameter: [
                    {
                        name: 'coverage-information',
                        part: [
                            {
                                name: 'coverage',
                                valueReference: {
                                    reference: coverage.id ? `Coverage/${coverage.id}` : undefined
                                }
                            },
                            {
                                name: 'extension',
                                valueExtension: coverageInfoExtension
                            }
                        ]
                    }
                ]
            }
        };
    }

    /**
     * Creates a Launch DTR SMART App card.
     *
     * When the payer determines that additional documentation is needed
     * (e.g., for prior authorization), this card provides a SMART App launch
     * link to the Da Vinci DTR (Documentation Templates and Rules) application.
     *
     * @param {Object} params
     * @param {Object} params.payerResponse - The payer CRD response
     * @param {Object} params.coverage - The FHIR Coverage resource
     * @param {Object} params.payerSource - Source attribution
     * @param {import('../multiTenancy/tenantContext').TenantContext} params.tenantContext
     * @returns {Object|null} CDS Card with SMART App link, or null
     */
    createLaunchDtrCard ({ payerResponse, coverage, payerSource, tenantContext }) {
        // Determine the DTR launch URL
        const dtrAppUrl = payerResponse.dtrLaunchUrl ||
            (tenantContext.features.dtrAppUrl) ||
            process.env.DTR_SMART_APP_URL;

        if (!dtrAppUrl) {
            logWarn('Prior auth required but no DTR SMART App URL configured', {
                tenantId: tenantContext.tenantId
            });
            return null;
        }

        // Build the SMART App launch context
        const appContext = {};
        if (payerResponse.questionnaireId) {
            appContext.questionnaire = payerResponse.questionnaireId;
        }
        if (coverage.id) {
            appContext.coverage = `Coverage/${coverage.id}`;
        }
        if (payerResponse.priorAuthId) {
            appContext.priorAuth = payerResponse.priorAuthId;
        }

        return {
            uuid: generateUUID(),
            summary: 'Additional Documentation Required - Launch DTR',
            detail: payerResponse.documentationMessage ||
                'The payer requires additional documentation to complete the coverage determination. ' +
                'Launch the DTR application to fill out the required forms.',
            indicator: CARD_INDICATORS.WARNING,
            source: payerSource,
            links: [
                {
                    label: 'Launch DTR SMART App',
                    url: dtrAppUrl,
                    type: 'smart',
                    appContext: JSON.stringify(appContext)
                }
            ],
            suggestions: [
                {
                    label: 'Launch Documentation Templates and Rules',
                    uuid: generateUUID(),
                    isRecommended: true,
                    actions: [
                        {
                            type: 'launch',
                            description: 'Launch the DTR SMART App to complete required documentation',
                            resource: {
                                resourceType: 'Parameters',
                                parameter: [
                                    {
                                        name: 'appUrl',
                                        valueUrl: dtrAppUrl
                                    },
                                    {
                                        name: 'appContext',
                                        valueString: JSON.stringify(appContext)
                                    }
                                ]
                            }
                        }
                    ]
                }
            ]
        };
    }

    /**
     * Creates External Reference cards for payer documentation links.
     *
     * These cards provide links to external payer documentation such as
     * coverage policies, prior authorization forms, and clinical guidelines.
     *
     * @param {Object} params
     * @param {Object} params.payerResponse - The payer CRD response
     * @param {Object} params.payerSource - Source attribution
     * @returns {Object[]} Array of CDS Cards
     */
    createExternalReferenceCards ({ payerResponse, payerSource }) {
        const cards = [];

        // Check for documentation links in the payer response
        const docLinks = payerResponse.documentationLinks ||
            payerResponse.externalReferences || [];

        if (!Array.isArray(docLinks) || docLinks.length === 0) {
            return cards;
        }

        // Group related links into a single card when possible
        const links = docLinks.map(link => ({
            label: link.label || link.title || 'Payer Documentation',
            url: link.url || link.href,
            type: link.type || 'absolute'
        })).filter(link => link.url);

        if (links.length > 0) {
            cards.push({
                uuid: generateUUID(),
                summary: 'Payer Coverage Documentation Available',
                detail: payerResponse.documentationSummary ||
                    'The payer has provided documentation related to coverage requirements ' +
                    'for this service. Review the linked resources for details.',
                indicator: CARD_INDICATORS.INFO,
                source: payerSource,
                links
            });
        }

        return cards;
    }

    /**
     * Creates Instructions cards with text-based guidance from the payer.
     *
     * These cards contain informational text about coverage policies,
     * limitations, or recommended clinical alternatives.
     *
     * @param {Object} params
     * @param {Object} params.payerResponse - The payer CRD response
     * @param {Object} params.payerSource - Source attribution
     * @param {string|null} params.coverageAssertion - The coverage assertion code
     * @returns {Object[]} Array of CDS Cards
     */
    createInstructionCards ({ payerResponse, payerSource, coverageAssertion }) {
        const cards = [];

        // Add instructions from the payer response
        const instructions = payerResponse.instructions || [];

        if (Array.isArray(instructions)) {
            for (const instruction of instructions) {
                if (!instruction.text && !instruction.summary) {
                    continue;
                }

                cards.push({
                    uuid: generateUUID(),
                    summary: instruction.summary || 'Coverage Guidance',
                    detail: instruction.text || instruction.detail,
                    indicator: instruction.indicator || CARD_INDICATORS.INFO,
                    source: payerSource
                });
            }
        }

        // Add a summary card based on the coverage assertion if no
        // specific instruction cards were already created
        if (cards.length === 0 && coverageAssertion) {
            const summaryCard = this.createAssertionSummaryCard(coverageAssertion, payerSource);
            if (summaryCard) {
                cards.push(summaryCard);
            }
        }

        return cards;
    }

    /**
     * Creates a summary card based on the coverage assertion.
     * @param {string} assertion - The coverage assertion code
     * @param {Object} payerSource - Source attribution
     * @returns {Object|null} CDS Card
     */
    createAssertionSummaryCard (assertion, payerSource) {
        switch (assertion) {
            case COVERAGE_ASSERTIONS.COVERED:
                return {
                    uuid: generateUUID(),
                    summary: 'Service is Covered',
                    detail: 'The requested service/product is covered under the patient\'s current plan. ' +
                        'No additional action is required.',
                    indicator: CARD_INDICATORS.INFO,
                    source: payerSource
                };

            case COVERAGE_ASSERTIONS.NOT_COVERED:
                return {
                    uuid: generateUUID(),
                    summary: 'Service is Not Covered',
                    detail: 'The requested service/product is not covered under the patient\'s current plan. ' +
                        'Consider discussing alternative options with the patient.',
                    indicator: CARD_INDICATORS.CRITICAL,
                    source: payerSource
                };

            case COVERAGE_ASSERTIONS.PRIOR_AUTH:
                return {
                    uuid: generateUUID(),
                    summary: 'Prior Authorization Required',
                    detail: 'Prior authorization is required for this service/product. ' +
                        'Complete the required documentation using the DTR application to initiate the PA process.',
                    indicator: CARD_INDICATORS.WARNING,
                    source: payerSource
                };

            case COVERAGE_ASSERTIONS.DOCUMENTATION:
                return {
                    uuid: generateUUID(),
                    summary: 'Additional Documentation Needed',
                    detail: 'The payer requires additional documentation to determine coverage ' +
                        'for this service/product. Please provide the requested information.',
                    indicator: CARD_INDICATORS.WARNING,
                    source: payerSource
                };

            case COVERAGE_ASSERTIONS.CONDITIONAL:
                return {
                    uuid: generateUUID(),
                    summary: 'Coverage Determination Pending',
                    detail: 'Coverage for this service/product cannot be fully determined with the available ' +
                        'information. Additional details may be needed.',
                    indicator: CARD_INDICATORS.WARNING,
                    source: payerSource
                };

            default:
                return null;
        }
    }

    /**
     * Extracts the coverage assertion code from the payer response.
     * @param {Object} payerResponse - The payer CRD response
     * @returns {string|null} Coverage assertion code
     */
    extractCoverageAssertion (payerResponse) {
        if (!payerResponse) {
            return null;
        }

        // Direct assertion field
        if (payerResponse.coverageAssertion) {
            return payerResponse.coverageAssertion;
        }

        // Look in the response's coverage-information extension
        if (payerResponse.coverageInformation) {
            return payerResponse.coverageInformation.assertion || null;
        }

        // Look in system actions for coverage-information
        if (payerResponse.systemActions && Array.isArray(payerResponse.systemActions)) {
            for (const action of payerResponse.systemActions) {
                if (action.resource && action.resource.extension) {
                    const covInfoExt = Array.isArray(action.resource.extension)
                        ? action.resource.extension.find(e => e.url === COVERAGE_INFO_EXTENSION_URL)
                        : null;

                    if (covInfoExt && covInfoExt.extension) {
                        const coveredExt = covInfoExt.extension.find(e => e.url === 'covered');
                        if (coveredExt) {
                            return coveredExt.valueCode === 'not-covered'
                                ? COVERAGE_ASSERTIONS.NOT_COVERED
                                : COVERAGE_ASSERTIONS.COVERED;
                        }
                    }
                }
            }
        }

        return null;
    }

    /**
     * Determines whether prior authorization is required based on the payer response.
     * @param {Object} payerResponse - The payer CRD response
     * @param {string|null} coverageAssertion - Extracted coverage assertion
     * @returns {boolean}
     */
    isPriorAuthRequired (payerResponse, coverageAssertion) {
        // Explicit assertion
        if (coverageAssertion === COVERAGE_ASSERTIONS.PRIOR_AUTH) {
            return true;
        }

        // Explicit flag in response
        if (payerResponse.priorAuthRequired === true) {
            return true;
        }

        // Check coverage-information for pa-needed
        if (payerResponse.coverageInformation &&
            payerResponse.coverageInformation.paNeeded === 'auth-needed') {
            return true;
        }

        return false;
    }
}

module.exports = {
    CardGenerator,
    COVERAGE_INFO_EXTENSION_URL,
    CRD_COVERAGE_INFO_SYSTEM,
    CARD_INDICATORS,
    COVERAGE_ASSERTIONS
};
